services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: template
      POSTGRES_USER: template
      POSTGRES_PASSWORD: template
    volumes:
      - postgres_data:/var/lib/postgresql

  template:
    image: Template:1.0-latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres

volumes:
  postgres_data:
